"""The Area Dashboard render: a pure, read-only Projection of an Area and its
Projects as Markdown (`dashboard-structure.md`: Title, Purpose, Navigation,
Contents, Related). No I/O anywhere in this file.
"""

import ast
import copy
import re
from pathlib import Path

import pytest

from ohtli.representation import area_dashboard
from ohtli.representation.area_dashboard import GENERATED_MARKER, render

AREA_LINK = "[[areas/health|Health]]"


def _project(name, *, status="planned", context="operational"):
    return {"link": f"[[projects/{name.lower()}|{name}]]", "status": status, "context": context}


def _render(projects=(), *, historical=False, title="Health"):
    return render(area_title=title, area_link=AREA_LINK, area_historical=historical, projects=list(projects))


def _section(text, heading):
    """The lines under `heading`, up to the next heading or `---` rule."""
    lines = text.splitlines()
    start = lines.index(heading) + 1
    body = []
    for line in lines[start:]:
        if line.startswith("#") or line == "---":
            break
        body.append(line)
    return [line for line in body if line.strip()]


# ---- the generated-file marker ------------------------------------------------------


def test_the_first_line_is_exactly_the_generated_marker():
    assert _render().splitlines()[0] == GENERATED_MARKER


def test_it_never_starts_with_frontmatter_so_no_scan_mistakes_it_for_a_note():
    text = _render()

    assert not text.startswith("---")
    assert not re.match(r"---\s*\n", text)


def test_the_marker_is_a_well_formed_html_comment_without_a_double_hyphen_inside():
    assert GENERATED_MARKER.startswith("<!--") and GENERATED_MARKER.endswith("-->")
    inner = GENERATED_MARKER[len("<!--") : -len("-->")]
    assert "--" not in inner, "`--` is not valid inside an HTML comment"
    assert "\n" not in GENERATED_MARKER, "the marker is a single line"


# ---- structure ----------------------------------------------------------------------


def test_the_title_is_the_one_h1_and_names_the_area():
    lines = _render(title="Ñandú Área").splitlines()

    assert [line for line in lines if re.match(r"# [^#]", line)] == ["# Ñandú Área: Area Dashboard"]


def test_the_four_h2_sections_follow_dashboard_structure_in_order():
    headings = re.findall(r"^## .+$", _render(), re.MULTILINE)

    assert headings == ["## Purpose", "## Navigation", "## Contents", "## Related"]


def test_contents_always_has_both_subsections_in_a_fixed_order():
    headings = re.findall(r"^### .+$", _render(), re.MULTILINE)

    assert headings == ["### Operational", "### Historical"]


def test_purpose_names_the_area_and_asks_the_one_question():
    (purpose,) = _section(_render(), "## Purpose")

    assert purpose == f"Which Projects belong to {AREA_LINK}, and where does each stand?"


def test_navigation_links_the_workspace_the_areas_index_and_the_area_itself():
    assert _section(_render(), "## Navigation") == ["- [[workspace]]", "- [[areas/index]]", f"- {AREA_LINK}"]


def test_related_links_the_projects_index():
    assert _section(_render(), "## Related") == ["- [[projects/index]]"]


def test_the_generated_note_says_not_to_edit_and_how_to_regenerate():
    (note,) = [line for line in _render().splitlines() if line.startswith("_Generated by Ohtli")]

    assert "Do not edit this file" in note
    assert 'ohtli area-dashboard "<Area>" --write' in note


def test_the_regenerate_hint_never_contains_the_real_title():
    """A title with quotes or backticks must not be able to break the hint."""
    def hint(title):
        return [line for line in _render(title=title).splitlines() if line.startswith("_Generated by Ohtli")]

    assert hint('Evil "Area" `x`') == hint("Health")


# ---- the Projects -------------------------------------------------------------------


def test_operational_and_historical_projects_are_listed_under_their_own_subsection():
    text = _render([_project("Alpha"), _project("Old", context="historical")])

    assert _section(text, "### Operational") == ["- [[projects/alpha|Alpha]] (status: planned)"]
    assert _section(text, "### Historical") == ["- [[projects/old|Old]] (status: planned)"]


def test_links_are_used_verbatim():
    link = "[[projects/nested/deep|A | odd title]]"

    text = _render([{"link": link, "status": "planned", "context": "operational"}])

    assert f"- {link} (status: planned)" in text.splitlines()


@pytest.mark.parametrize(
    "project",
    [
        {"link": "[[projects/a|A]]", "status": "planned"},  # no `context` key at all (pre-Phase-13 note)
        {"link": "[[projects/a|A]]", "status": "planned", "context": None},
        {"link": "[[projects/a|A]]", "status": "planned", "context": "operational"},
    ],
    ids=["missing-key", "none", "operational"],
)
def test_only_an_explicit_historical_context_is_historical(project):
    text = _render([project])

    assert _section(text, "### Operational") == ["- [[projects/a|A]] (status: planned)"]
    assert _section(text, "### Historical") == ["None."]


@pytest.mark.parametrize("status", [None, ""], ids=["none", "empty"])
def test_a_missing_status_is_shown_as_none(status):
    text = _render([_project("A", status=status)])

    assert _section(text, "### Operational") == ["- [[projects/a|A]] (status: none)"]


def test_a_project_without_a_status_key_is_shown_as_none():
    text = _render([{"link": "[[projects/a|A]]", "context": "operational"}])

    assert _section(text, "### Operational") == ["- [[projects/a|A]] (status: none)"]


def test_an_area_without_projects_shows_none_in_both_subsections():
    text = _render([])

    assert _section(text, "### Operational") == ["None."]
    assert _section(text, "### Historical") == ["None."]


def test_only_historical_projects_leave_operational_empty():
    text = _render([_project("Old", context="historical")])

    assert _section(text, "### Operational") == ["None."]
    assert _section(text, "### Historical") == ["- [[projects/old|Old]] (status: planned)"]


def test_projects_keep_the_order_the_caller_gave_them():
    """The caller sorts; render does not reorder."""
    text = _render([_project("Zeta"), _project("Alpha")])

    assert _section(text, "### Operational") == [
        "- [[projects/zeta|Zeta]] (status: planned)",
        "- [[projects/alpha|Alpha]] (status: planned)",
    ]


def test_a_project_appears_in_exactly_one_subsection():
    text = _render([_project("A"), _project("B", context="historical"), _project("C")])

    for name in ("A", "B", "C"):
        assert text.count(f"[[projects/{name.lower()}|{name}]]") == 1


# ---- the Area's own state -----------------------------------------------------------


def test_a_historical_area_says_so_under_the_title():
    lines = _render(historical=True).splitlines()

    assert "This Area is historical (archived)." in lines
    assert lines.index("This Area is historical (archived).") < lines.index("## Purpose")


def test_an_operational_area_says_nothing_about_being_historical():
    assert "historical (archived)" not in _render(historical=False)


# ---- byte stability -----------------------------------------------------------------


def test_the_text_ends_with_exactly_one_newline():
    text = _render([_project("A")])

    assert text.endswith("\n") and not text.endswith("\n\n")


def test_the_same_input_always_renders_the_same_text():
    projects = [_project("A"), _project("B", context="historical")]

    assert _render(projects) == _render(projects)


def test_the_output_carries_no_date_or_time():
    text = _render([_project("A")], historical=True)

    assert not re.search(r"\d{4}-\d{2}-\d{2}", text)
    assert not re.search(r"\d{1,2}:\d{2}", text)


def test_rendering_does_not_mutate_its_input():
    projects = [_project("A"), _project("B", context="historical")]
    before = copy.deepcopy(projects)

    _render(projects)

    assert projects == before


# ---- purity -------------------------------------------------------------------------


def test_the_module_imports_nothing_that_could_do_io_or_read_a_clock():
    """The Projection is a pure transformation. Restricting its imports to
    these two is what guarantees that: no `vault_io`, no `pathlib`, no
    `datetime`, no `os`."""
    tree = ast.parse(Path(area_dashboard.__file__).read_text(encoding="utf-8"))
    imported = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            imported |= {alias.name.split(".")[0] for alias in node.names}
        elif isinstance(node, ast.ImportFrom):
            imported.add((node.module or "").split(".")[0])

    assert imported <= {"__future__", "typing"}, f"unexpected imports: {sorted(imported)}"
