from __future__ import annotations

from typing import Any, Sequence

# First line of every generated Area Dashboard. `vault_io.generated` overwrites
# an existing file only if its first line is exactly this, so a hand-written
# note is never clobbered. It starts with `<`, never `---`, so no scan can
# mistake a dashboard for a Domain Object note (they all require frontmatter).
# No `--` inside: that sequence is not valid within an HTML comment.
GENERATED_MARKER = (
    "<!-- ohtli:generated area-dashboard | regenerated whole, never merged; "
    "edits are overwritten -->"
)

_HISTORICAL = "historical"


def render(
    *,
    area_title: str,
    area_link: str,
    area_historical: bool,
    projects: Sequence[dict[str, Any]],
) -> str:
    """Render an Area Dashboard: a read-only Projection of one Area and the
    Projects that belong to it (`current-representation.md`, Projection
    semantics), in the shape `dashboard-structure.md` prescribes: Title,
    Purpose, Navigation, Contents, Related.

    Pure: no I/O, no dates, no clock. The same input always renders the same
    text, so regenerating an unchanged vault produces an identical file. It
    answers one question, per `design-principles.md` (Purpose-Driven): which
    Projects belong to this Area, and where does each stand?

    `projects` are shown in the order given (the caller sorts them); each item
    needs `link` (an already-built wikilink), `status` and `context`. A Project
    is historical only if its `context` is `"historical"`; a missing `context`
    counts as operational, because nothing marks a note historical until
    Archive does.

    The regenerate hint deliberately names `"<Area>"` instead of the real
    title, so a title with quotes or backticks can never break it.
    """
    operational = [p for p in projects if p.get("context") != _HISTORICAL]
    historical = [p for p in projects if p.get("context") == _HISTORICAL]

    lines = [GENERATED_MARKER, "", f"# {area_title}: Area Dashboard", ""]
    if area_historical:
        lines += ["This Area is historical (archived).", ""]
    lines += [
        '_Generated by Ohtli from the Area and Project notes. Do not edit this file: it is overwritten '
        'when regenerated with `ohtli area-dashboard "<Area>" --write`._',
        "",
        "## Purpose",
        "",
        f"Which Projects belong to {area_link}, and where does each stand?",
        "",
        "---",
        "",
        "## Navigation",
        "",
        "- [[workspace]]",
        "- [[areas/index]]",
        f"- {area_link}",
        "",
        "---",
        "",
        "## Contents",
        "",
        "### Operational",
        "",
        *_project_lines(operational),
        "",
        "### Historical",
        "",
        *_project_lines(historical),
        "",
        "---",
        "",
        "## Related",
        "",
        "- [[projects/index]]",
    ]
    return "\n".join(lines) + "\n"


def _project_lines(projects: Sequence[dict[str, Any]]) -> list[str]:
    if not projects:
        return ["None."]
    return [f"- {p['link']} (status: {p.get('status') or 'none'})" for p in projects]
